# Generated by Django 6.0.4 on 2026-05-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "body",
                    models.TextField(
                        help_text="Supports basic HTML (bold, italic, links, etc.)"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this post without deleting it.",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Post",
                "verbose_name_plural": "News Posts",
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
